on:
  push:
    branches: ["main"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      PORT: 8080
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'
          cache: 'npm'
      - run: npm ci
      - name: Log in to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{github.repository}}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./DockerFile
          push: true
          tags: ${{github.repository}}:${{github.sha}}
          labels: ${{steps.meta.outputs.labels}}
          build-args: |
            PORT=${{env.PORT}}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}